version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile    
    container_name: api
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db
      NODE_ENV: development
    volumes:
      - .:/app  

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

volumes:
  pgdata:
